#+title: Dasy Docs
#+options: toc: t
* Current Status
Dasy is currently in pre-alpha. The language's core is still being designed and implemented.
* Syntax
Dasy has a clojure-inspired lisp syntax with some influences from python. Some constructs are dasy-specific.
** Tuples
Tuples are signified by a quoted list such as ~'(1 2 3)~
The vyper equivalent is ~(1, 2, 3)~

* Core Macros
** ~defn~

~(defn fn-name args [return-type] visibility & body)~

This special form declares and defines a function within a smart contract.

The ~args~ list may be an empty list, but must be present. Returning multiple values requires declaring the return type as a tuple.

The ~return-type~ object is optional. If present, it may be a single keyword representing the return type, or it may be a tuple of keywords for returning multiple values.

The ~visibility~ object may also be a keyword or list of keywords. Valid values are:

- ~:external~
- ~:internal~
- ~:payable~
- ~:view~
- ~:pure~
- ~(nonreentrant "lock-name")~

#+begin_src clojure
(defn noArgs [] :external (pass))

(defn setNum [:uint256 x] :external (pass))

(defn addNums [:uint256 x y] :uint256 [:external :pure]
  (+ x y))

(defn addAndSub [:uint256 x y] '(:uint256 :uint256) [:external :pure]
  '((+ x y) (- x y)))
#+end_src
** ~defvar~
~(defvar variable-name type [value])~

This special form declares and optionally assigns a value to a variable.

Outside of a ~defn~ form, variables are stored in ~storage~ and accessible via ~self.variable-name~.

Inside a ~defn~ form, variables are stored in ~memory~ and accessible directly.

The ~value~ form is optional.

#+begin_src clojure
(defvar owner (public :address))
(defvar enabled :bool)

(defn foo [] :external
  (defvar owner_memory :address self/owner)) ;; declare copy in memory
#+end_src
** ~setv~
~(setv name value)~

This special form assigns a value to a name. It is roughly equivalent to the equal sign ~=~ in Vyper.
#+begin_src clojure
;; Create a string variable that can store maximum 100 characters
(defvar greet (public (string 100)))

(defn __init__ [] :external
    (setv self/greet "Hello World")) ;; in vyper: self.greet = "Hello World"
#+end_src
** ~/~

~(setv self/foo bar)~

Access object attributes. ~obj/name~ is shorthand for ~(. obj name)~
